#if WINDOWS

using Microsoft.UI.Xaml.Input;
using Windows.System;
using Windows.Win32.UI.Input.KeyboardAndMouse;

namespace Plugin.Maui.KeyListener;

internal static partial class KeyboardKeysExtensions
{
	/// <remarks>
	/// https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
	/// </remarks>
	public static VirtualKey ToVirtualKey(KeyboardKeys keyboardKey) => keyboardKey switch
	{
		KeyboardKeys.None => VirtualKey.None,
		KeyboardKeys.A => VirtualKey.A,
		KeyboardKeys.B => VirtualKey.B,
		KeyboardKeys.C => VirtualKey.C,
		KeyboardKeys.D => VirtualKey.D,
		KeyboardKeys.E => VirtualKey.E,
		KeyboardKeys.F => VirtualKey.F,
		KeyboardKeys.G => VirtualKey.G,
		KeyboardKeys.H => VirtualKey.H,
		KeyboardKeys.I => VirtualKey.I,
		KeyboardKeys.J => VirtualKey.J,
		KeyboardKeys.K => VirtualKey.K,
		KeyboardKeys.L => VirtualKey.L,
		KeyboardKeys.M => VirtualKey.M,
		KeyboardKeys.N => VirtualKey.N,
		KeyboardKeys.O => VirtualKey.O,
		KeyboardKeys.P => VirtualKey.P,
		KeyboardKeys.Q => VirtualKey.Q,
		KeyboardKeys.R => VirtualKey.R,
		KeyboardKeys.S => VirtualKey.S,
		KeyboardKeys.T => VirtualKey.T,
		KeyboardKeys.U => VirtualKey.U,
		KeyboardKeys.V => VirtualKey.V,
		KeyboardKeys.W => VirtualKey.W,
		KeyboardKeys.X => VirtualKey.X,
		KeyboardKeys.Y => VirtualKey.Y,
		KeyboardKeys.Z => VirtualKey.Z,
		KeyboardKeys.Number0 => VirtualKey.Number0,
		KeyboardKeys.Number1 => VirtualKey.Number1,
		KeyboardKeys.Number2 => VirtualKey.Number2,
		KeyboardKeys.Number3 => VirtualKey.Number3,
		KeyboardKeys.Number4 => VirtualKey.Number4,
		KeyboardKeys.Number5 => VirtualKey.Number5,
		KeyboardKeys.Number6 => VirtualKey.Number6,
		KeyboardKeys.Number7 => VirtualKey.Number7,
		KeyboardKeys.Number8 => VirtualKey.Number8,
		KeyboardKeys.Number9 => VirtualKey.Number9,
		KeyboardKeys.Escape => VirtualKey.Escape,
		KeyboardKeys.F1 => VirtualKey.F1,
		KeyboardKeys.F2 => VirtualKey.F2,
		KeyboardKeys.F3 => VirtualKey.F3,
		KeyboardKeys.F4 => VirtualKey.F4,
		KeyboardKeys.F5 => VirtualKey.F5,
		KeyboardKeys.F6 => VirtualKey.F6,
		KeyboardKeys.F7 => VirtualKey.F7,
		KeyboardKeys.F8 => VirtualKey.F8,
		KeyboardKeys.F9 => VirtualKey.F9,
		KeyboardKeys.F10 => VirtualKey.F10,
		KeyboardKeys.F11 => VirtualKey.F11,
		KeyboardKeys.F12 => VirtualKey.F12,
		KeyboardKeys.PrintScreen => VirtualKey.Snapshot,
		KeyboardKeys.ScrollLock => VirtualKey.Scroll,
		KeyboardKeys.Pause => VirtualKey.Pause,
		KeyboardKeys.Minus => VirtualKey.Subtract, // -
		KeyboardKeys.Equals => VirtualKey.Add, // =
		KeyboardKeys.Backspace => VirtualKey.Back,
		KeyboardKeys.Tab => VirtualKey.Tab,
		KeyboardKeys.LeftBracket => (VirtualKey)VIRTUAL_KEY.VK_OEM_4,
		KeyboardKeys.RightBracket => (VirtualKey)VIRTUAL_KEY.VK_OEM_6,
		KeyboardKeys.Backslash => (VirtualKey)VIRTUAL_KEY.VK_OEM_5,
		KeyboardKeys.CapsLock => VirtualKey.CapitalLock,
		KeyboardKeys.Semicolon => (VirtualKey)VIRTUAL_KEY.VK_OEM_1,
		KeyboardKeys.Quote => (VirtualKey)VIRTUAL_KEY.VK_OEM_7,
		KeyboardKeys.Return => VirtualKey.Enter,
		KeyboardKeys.LeftShift => VirtualKey.LeftShift,
		KeyboardKeys.RightShift => VirtualKey.RightShift,
		KeyboardKeys.LeftControl => VirtualKey.LeftControl,
		KeyboardKeys.RightControl => VirtualKey.RightControl,
		KeyboardKeys.LeftAlt => VirtualKey.LeftMenu,
		KeyboardKeys.RightAlt => VirtualKey.RightMenu,
		KeyboardKeys.LeftCommand => VirtualKey.LeftWindows,
		KeyboardKeys.RightCommand => VirtualKey.RightWindows,
		KeyboardKeys.Space => VirtualKey.Space,
		KeyboardKeys.Insert => VirtualKey.Insert,
		KeyboardKeys.Delete => VirtualKey.Delete,
		KeyboardKeys.Home => VirtualKey.Home,
		KeyboardKeys.End => VirtualKey.End,
		KeyboardKeys.PageUp => VirtualKey.PageUp,
		KeyboardKeys.PageDown => VirtualKey.PageDown,
		KeyboardKeys.LeftArrow => VirtualKey.Left,
		KeyboardKeys.RightArrow => VirtualKey.Right,
		KeyboardKeys.UpArrow => VirtualKey.Up,
		KeyboardKeys.DownArrow => VirtualKey.Down,
		KeyboardKeys.NumLock => VirtualKey.NumberKeyLock,
		KeyboardKeys.NumPadDivide => VirtualKey.Divide,
		KeyboardKeys.NumPadMultiply => VirtualKey.Multiply,
		KeyboardKeys.NumPadMinus => VirtualKey.Subtract,
		KeyboardKeys.NumPadPlus => VirtualKey.Add,
		KeyboardKeys.NumPadEnter => VirtualKey.Enter,
		KeyboardKeys.NumPadPeriod => VirtualKey.Decimal,
		KeyboardKeys.NumPad0 => VirtualKey.NumberPad0,
		KeyboardKeys.NumPad1 => VirtualKey.NumberPad1,
		KeyboardKeys.NumPad2 => VirtualKey.NumberPad2,
		KeyboardKeys.NumPad3 => VirtualKey.NumberPad3,
		KeyboardKeys.NumPad4 => VirtualKey.NumberPad4,
		KeyboardKeys.NumPad5 => VirtualKey.NumberPad5,
		KeyboardKeys.NumPad6 => VirtualKey.NumberPad6,
		KeyboardKeys.NumPad7 => VirtualKey.NumberPad7,
		KeyboardKeys.NumPad8 => VirtualKey.NumberPad8,
		KeyboardKeys.NumPad9 => VirtualKey.NumberPad9,
		KeyboardKeys.Enter => VirtualKey.Enter,
		KeyboardKeys.Plus => VirtualKey.Add,
		KeyboardKeys.GraveAccent => (VirtualKey)VIRTUAL_KEY.VK_OEM_3,
		KeyboardKeys.Comma => (VirtualKey)VIRTUAL_KEY.VK_OEM_COMMA,
		KeyboardKeys.Period => (VirtualKey)VIRTUAL_KEY.VK_OEM_PERIOD,
		KeyboardKeys.Slash => (VirtualKey)VIRTUAL_KEY.VK_OEM_2,
		KeyboardKeys.Application => VirtualKey.Application,
		_ => VirtualKey.None
	};

	public static KeyboardKeys ToKeyboardKeys(this VirtualKey platformKey) => platformKey switch
	{
		VirtualKey.None => KeyboardKeys.None,
		VirtualKey.A => KeyboardKeys.A,
		VirtualKey.B => KeyboardKeys.B,
		VirtualKey.C => KeyboardKeys.C,
		VirtualKey.D => KeyboardKeys.D,
		VirtualKey.E => KeyboardKeys.E,
		VirtualKey.F => KeyboardKeys.F,
		VirtualKey.G => KeyboardKeys.G,
		VirtualKey.H => KeyboardKeys.H,
		VirtualKey.I => KeyboardKeys.I,
		VirtualKey.J => KeyboardKeys.J,
		VirtualKey.K => KeyboardKeys.K,
		VirtualKey.L => KeyboardKeys.L,
		VirtualKey.M => KeyboardKeys.M,
		VirtualKey.N => KeyboardKeys.N,
		VirtualKey.O => KeyboardKeys.O,
		VirtualKey.P => KeyboardKeys.P,
		VirtualKey.Q => KeyboardKeys.Q,
		VirtualKey.R => KeyboardKeys.R,
		VirtualKey.S => KeyboardKeys.S,
		VirtualKey.T => KeyboardKeys.T,
		VirtualKey.U => KeyboardKeys.U,
		VirtualKey.V => KeyboardKeys.V,
		VirtualKey.W => KeyboardKeys.W,
		VirtualKey.X => KeyboardKeys.X,
		VirtualKey.Y => KeyboardKeys.Y,
		VirtualKey.Z => KeyboardKeys.Z,
		VirtualKey.Number0 => KeyboardKeys.Number0,
		VirtualKey.Number1 => KeyboardKeys.Number1,
		VirtualKey.Number2 => KeyboardKeys.Number2,
		VirtualKey.Number3 => KeyboardKeys.Number3,
		VirtualKey.Number4 => KeyboardKeys.Number4,
		VirtualKey.Number5 => KeyboardKeys.Number5,
		VirtualKey.Number6 => KeyboardKeys.Number6,
		VirtualKey.Number7 => KeyboardKeys.Number7,
		VirtualKey.Number8 => KeyboardKeys.Number8,
		VirtualKey.Number9 => KeyboardKeys.Number9,
		VirtualKey.Escape => KeyboardKeys.Escape,
		VirtualKey.F1 => KeyboardKeys.F1,
		VirtualKey.F2 => KeyboardKeys.F2,
		VirtualKey.F3 => KeyboardKeys.F3,
		VirtualKey.F4 => KeyboardKeys.F4,
		VirtualKey.F5 => KeyboardKeys.F5,
		VirtualKey.F6 => KeyboardKeys.F6,
		VirtualKey.F7 => KeyboardKeys.F7,
		VirtualKey.F8 => KeyboardKeys.F8,
		VirtualKey.F9 => KeyboardKeys.F9,
		VirtualKey.F10 => KeyboardKeys.F10,
		VirtualKey.F11 => KeyboardKeys.F11,
		VirtualKey.F12 => KeyboardKeys.F12,
		VirtualKey.Snapshot => KeyboardKeys.PrintScreen,
		VirtualKey.Scroll => KeyboardKeys.ScrollLock,
		VirtualKey.Pause => KeyboardKeys.Pause,
		(VirtualKey)VIRTUAL_KEY.VK_OEM_3 => KeyboardKeys.GraveAccent,
		(VirtualKey)VIRTUAL_KEY.VK_OEM_MINUS => KeyboardKeys.Minus,
		(VirtualKey)VIRTUAL_KEY.VK_OEM_PLUS => KeyboardKeys.Equals, // VK_OEM_PLUS is the same as the Equals key
		VirtualKey.Back => KeyboardKeys.Backspace,
		VirtualKey.Tab => KeyboardKeys.Tab,
		(VirtualKey)VIRTUAL_KEY.VK_OEM_4 => KeyboardKeys.LeftBracket,
		(VirtualKey)VIRTUAL_KEY.VK_OEM_6 => KeyboardKeys.RightBracket,
		(VirtualKey)VIRTUAL_KEY.VK_OEM_5 => KeyboardKeys.Backslash,
		VirtualKey.CapitalLock => KeyboardKeys.CapsLock,
		(VirtualKey)VIRTUAL_KEY.VK_OEM_1 => KeyboardKeys.Semicolon,
		(VirtualKey)VIRTUAL_KEY.VK_OEM_7 => KeyboardKeys.Quote,
		VirtualKey.Enter => KeyboardKeys.Return,
		VirtualKey.LeftShift => KeyboardKeys.LeftShift,
		VirtualKey.RightShift => KeyboardKeys.RightShift,
		VirtualKey.LeftControl => KeyboardKeys.LeftControl,
		VirtualKey.RightControl => KeyboardKeys.RightControl,
		VirtualKey.LeftMenu => KeyboardKeys.LeftAlt,
		VirtualKey.RightMenu => KeyboardKeys.RightAlt,
		VirtualKey.LeftWindows => KeyboardKeys.LeftCommand,
		VirtualKey.RightWindows => KeyboardKeys.RightCommand,
		VirtualKey.Space => KeyboardKeys.Space,
		VirtualKey.Insert => KeyboardKeys.Insert,
		VirtualKey.Delete => KeyboardKeys.Delete,
		VirtualKey.Home => KeyboardKeys.Home,
		VirtualKey.End => KeyboardKeys.End,
		VirtualKey.PageUp => KeyboardKeys.PageUp,
		VirtualKey.PageDown => KeyboardKeys.PageDown,
		VirtualKey.Left => KeyboardKeys.LeftArrow,
		VirtualKey.Right => KeyboardKeys.RightArrow,
		VirtualKey.Up => KeyboardKeys.UpArrow,
		VirtualKey.Down => KeyboardKeys.DownArrow,
		VirtualKey.NumberKeyLock => KeyboardKeys.NumLock,
		VirtualKey.Divide => KeyboardKeys.NumPadDivide,
		VirtualKey.Multiply => KeyboardKeys.NumPadMultiply,
		VirtualKey.Subtract => KeyboardKeys.NumPadMinus,
		VirtualKey.Add => KeyboardKeys.NumPadPlus,
		VirtualKey.NumberPad0 => KeyboardKeys.NumPad0,
		VirtualKey.NumberPad1 => KeyboardKeys.NumPad1,
		VirtualKey.NumberPad2 => KeyboardKeys.NumPad2,
		VirtualKey.NumberPad3 => KeyboardKeys.NumPad3,
		VirtualKey.NumberPad4 => KeyboardKeys.NumPad4,
		VirtualKey.NumberPad5 => KeyboardKeys.NumPad5,
		VirtualKey.NumberPad6 => KeyboardKeys.NumPad6,
		VirtualKey.NumberPad7 => KeyboardKeys.NumPad7,
		VirtualKey.NumberPad8 => KeyboardKeys.NumPad8,
		VirtualKey.NumberPad9 => KeyboardKeys.NumPad9,
		VirtualKey.Decimal => KeyboardKeys.NumPadPeriod,
		(VirtualKey)VIRTUAL_KEY.VK_OEM_COMMA => KeyboardKeys.Comma,
		(VirtualKey)VIRTUAL_KEY.VK_OEM_PERIOD => KeyboardKeys.Period,
		(VirtualKey)VIRTUAL_KEY.VK_OEM_2 => KeyboardKeys.Slash,
		VirtualKey.Application => KeyboardKeys.Application,
		_ => KeyboardKeys.None
	};

	static bool IsModifierKey(this VirtualKey key) => key is
		VirtualKey.Shift or
		VirtualKey.LeftShift or
		VirtualKey.RightShift or
		VirtualKey.Control or
		VirtualKey.LeftControl or
		VirtualKey.RightControl or
		VirtualKey.Menu or
		VirtualKey.LeftMenu or
		VirtualKey.RightMenu or
		VirtualKey.LeftWindows or
		VirtualKey.RightWindows;

	public static char ToChar(this VirtualKey key) => (char)Windows.Win32.PInvoke.MapVirtualKey((uint)key, MAP_VIRTUAL_KEY_TYPE.MAPVK_VK_TO_CHAR);

	internal static KeyPressedEventArgs ToKeyPressedEventArgs(this KeyRoutedEventArgs e)
	{
		VirtualKeyModifiers virtualKeyModifiers = KeyboardModifiersExtensions.GetVirtualKeyModifiers();
		var vk = e.Key.IsModifierKey() ? (VirtualKey)Windows.Win32.PInvoke.MapVirtualKey(e.KeyStatus.ScanCode, MAP_VIRTUAL_KEY_TYPE.MAPVK_VSC_TO_VK_EX) : e.Key;
		return new KeyPressedEventArgs
		{
			Modifiers = virtualKeyModifiers.ToKeyboardModifiers(),
			Key = vk.ToKeyboardKeys(),
			KeyChar = vk.ToChar(),
		};
	}
}
#endif